# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160825_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.FileField(upload_to=b'')),
            ],
        ),
    ]
