# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160918_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='time',
        ),
    ]
