# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160918_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='host',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
