# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160918_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
